### ISSUE TITLE
acore-docker-ac-eluna-ts-dev-1 can‘t ready

### ISSUE THREAD

**Issue by chongqingbaihuo** [azerothcore/acore-docker#14]
acore-docker-ac-eluna-ts-dev-1 can‘t ready
os:Ubuntu 20.04.5 LTS        and  centos 7.9.2009

docker compose version v2.15.1
docker version 20.10.23, build 7155243
docker image ： 

acore/ac-wotlk-client-data:7.0.0-dev.0 
acore/ac-wotlk-worldserver:7.0.0-dev.0 
acore/ac-wotlk-authserver:7.0.0-dev.0
acore/eluna-ts:master

two systems are the same error

```
acore-docker-ac-worldserver-1 | Calendar deletion of old events.
acore-docker-ac-worldserver-1 | Calendar deletion of old events.
acore-docker-ac-eluna-ts-dev-1 exited with code 1
acore-docker-ac-eluna-ts-dev-1 exited with code 1

root@ecs-861d-0728695:~# docker logs acore-docker-ac-eluna-ts-dev-1
touch: index.ts: Permission denied
touch: index.ts: Permission denied
touch: index.ts: Permission denied
touch: index.ts: Permission denied
touch: index.ts: Permission denied
touch: index.ts: Permission denied
touch: index.ts: Permission denied
```

thanks!

**Comment by Yehonal** [comment]
Can you please tell me which OS do you use?

**Comment by chongqingbaihuo** [comment]
> Can you please tell me which OS do you use?

Ubuntu 20.04.5 LTS

**Comment by Yehonal** [comment]
> > Can you please tell me which OS do you use?
> 
> Ubuntu 20.04.5 LTS

Please, run this command inside the acore-docker repository: 

```bash
ls -al scripts/typescript
```

and paste the output here

**Comment by chongqingbaihuo** [comment]
> > > Can you please tell me which OS do you use?
> > 
> > 
> > Ubuntu 20.04.5 LTS
> 
> Please, run this command inside the acore-docker repository:
> 
> ```shell
> ls -al scripts/typescript
> ```
> 
> and paste the output here

[root@ecs-9b55-0728005 acore-docker-master]#  ls -al scripts/typescript
total 8
drwxr-xr-x 3 root root  79 Jan 23 23:31 .
drwxr-xr-x 4 root root  35 Jan 23 23:31 ..
drwxr-xr-x 2 root root  24 Jan 23 23:31 examples
-rw-r--r-- 1 root root   0 Jan 23 23:31 .gitkeep
-rw-r--r-- 1 root root 221 Jan 23 23:31 package.json
-rw-r--r-- 1 root root 526 Jan 23 23:31 tsconfig.json

**Comment by Yehonal** [comment]
ok, so the main problem here is that the repository folder is under `root` user, while the container of eluna-ts uses a non-root user, that means the container doesn't have enough permissions to write in your volume. So, unless you want to change the permissions of your folder, you can try this approach:

1. create a `docker-compose.override.yml` file in the same folder of your `docker-compose.yml` file
2. paste this inside:

```
version: '3.9'

services:
  ac-eluna-ts-dev:
    user: root
```

3. run `docker compose up` again

Explanation: The docker-compose.override.yml allows you to extend the original docker-compose without modifying it. In this case we are adding the `user:root` rule that, in your case, since your host folder is under root, it should allow eluna-ts to write on the host folder.

Let me know if it works


NOTE: we might not want eluna-ts enabled by default to avoid such problems with new users that just want to run acore-docker without scripting it.

**Comment by chongqingbaihuo** [comment]
Thank you very much. It's working

**Comment by Moon-developer** [comment]
Thank you, this was an issue I also had. Could we maybe add it to the docs as a troubleshoot?

**Comment by 55Honey** [comment]
> Thank you, this was an issue I also had. Could we maybe add it to the docs as a troubleshoot?

Everyone can provide a PR to improve the wiki. Feel free to enhance it with a "common errors" or "faq" section.
